FROM node:18-alpine

# 設定工作目錄
WORKDIR /app

# 複製 package.json 和 package-lock.json
COPY package*.json ./

# 安裝依賴
RUN npm install

# 暴露端口
EXPOSE 3000

# 設定環境變數
ENV CHOKIDAR_USEPOLLING=true

# 啟動開發伺服器
CMD ["npm", "start"]
